### ISSUE TITLE
Missing values in Caravan Attributes

### ISSUE THREAD

**Issue by jnthnroy** [kratzert/Caravan#16]
HI,

May be it is already detected, if not probably an easy task. 
I found 158 bassins where caravan's attributes are missing, mostly in GB collection but some in GR and AUS.
All have small area (less than suggested 100km2).

note: DK collection is all ok

Thank you and keep going!

**Comment by kratzert** [comment]
Hi @jnthnroy 

thanks for reporting this. It seems like the hydroatlas files contains some rows (basins) that shouldn't be there. Correct are only the 408 basins from CAMELS-GB that are listed in the attributes_caravan_camelsgb.csv. The HydroATLAS file seems to contain some smaller ones (>= 50km2 instead of >= 100km2, which was my initial threshold but was then raised to 100sqkm for the publication). I will make sure that these are removed from the new version that is about to be uploaded.

**Comment by Multihuntr** [comment]
Hi. Thanks for releasing a nice dataset.

I downloaded the v1.3 from Zenodo (Released May 2023) and it still has exactly 158 extra basins in the `attributes/{subdataset}/attributes_hydroatlas_{subdataset}.csv` files.
