### ISSUE TITLE
Caravan_extension_CH

### ISSUE THREAD

**Issue by marv-in** [kratzert/Caravan#21]
### Basin prefix

camelsch

### Zenodo DOI

https://doi.org/10.5281/zenodo.7928595

### Number of catchments

296

### Location of catchments

Switzerland (and bordering regions of neighboring countries)

### For which periods are streamflow records available in your dataset?

1981-01-01 to 2020-12-31

### Please list any sources of the data you contributed.

Streamflow data was provided by the Swiss Federal Office for the Environment (FOEN/BAFU). Further data providers are referenced and acknowledged in the corresponding publication of CAMELS-CH, available at the Zenodo repository.

### License

Creative Commons Attribution 4.0 International License [CC-BY-4.0]

### Additional context

The Caravan_extension_CH is published together with a CAMELS-CH dataset that aside of daily hydro-meteorological time series and static attributes contains additional information, e.g. on glacier data annual time series, Swiss lakes and further attributes.

### Checklist

- [X] I have uploaded my dataset on Zenodo, where it is accessible under the DOI provided above.
- [X] I used a basin prefix that is not yet used by any other Caravan sub-dataset (you can check this via the [Data Contributions discussion thread](https://github.com/kratzert/Caravan/discussions/10), where all accepted Caravan contributions are listed).
- [X] Permissive License: My data is available under a license that is compatible with the Caravan CC-BY-4.0 license (the easiest way to be sure about this is if your data uses CC-BY-4.0, too).

**Comment by kratzert** [comment]
Hi @marv-in 

thanks for your data contribution. I downloaded the data and ran a few checks and there are some minor issues that I would like you to correct, so that everything is consistent with the rest of the Caravan data.

- You say your basin prefix is `ch` but the subdirectories of your extension are called `camelsch`, while your filenames (of the timeseries files) and the names in your attribute files have the `ch` prefix. It would be great if you could streamline this so that all use the same basin prefix (folder names as well as gauge_ids). In the light of the naming of the rest of the camels datasets within Caravan, I would recommend `camelsch` but the choice is yours. 
- In your extension the directory is called `licences`, while in Caravan it is called `licenses`. Both are valid words for the same thing but for the sake of not having two folders within the dataset (after merging your extension) it would be great if you could rename it to `licenses`.
- Your shapefile includes more fields than the other shapefiles, but this is fine. However, it would be great if you could rename the values in the `gauge_id` field to also include the basin prefix (i.e. either `ch` or `camelsch` depending on your choice of the first point).

I hope these are easy things for you to fix. If you update the data, would be great if you update the Zenodo DOI in this issue.

**Comment by marv-in** [comment]
Hi @kratzert ,

the renaming of all suggested items is complete. I edited the above comment such that it now includes the Zenodo DOI reference to the updated version.

**Comment by kratzert** [comment]
Hi @marv-in,

I checked the data again and everything looks fine. Thank you so much for contributing to Caravan, good luck for the CAMELS-CH reviews and hopefully until soon.

Next steps are: I will close this issue, link your extension in the list of community extensions over in the discussion forum and announce it on Twitter.
