### ISSUE TITLE
[DATA CONTRIBUTION] CAMELS-ES

### ISSUE THREAD

**Issue by casadoj** [kratzert/Caravan#25]
### Basin prefix

es

### Zenodo DOI

10.5281/zenodo.8373021

### Number of catchments

269

### Location of catchments

Spain

### For which periods are streamflow records available in your dataset?

1st October 1991 to 30th September 2020

### Please list any sources of the data you contributed.

The discharge records are taken from the "Anuario de Aforos" (https://ceh.cedex.es/anuarioaforos/default.asp),
a public repository of hydrological records in Spain curated by CEDEX (Centro de Estudios y Experimentación 
de Obras Públicas) and supported by the gauging networks of the several water agencies in the country.

The European Flood Awareness System (EFAS) version 5.0 is part of the Copernicus Emergency Management Services (https://emergency.copernicus.eu/)
 * EFASv5 simulated discharge is publicly available in the Copernicus Climate Data Store (https://cds.climate.copernicus.eu)
 * EFAS static maps are publicly available in the Joint Research Centre data catalog (https://data.jrc.ec.europa.eu/dataset/f572c443-7466-4adf-87aa-c0847a169f23)
 * The EMO1 dataset is publicly available in the Joint Research Centre data catalog (http://data.europa.eu/89h/0bd84be4-cec8-4180-97a6-8b3adaac4d26 )
 
HydroATLAS is licensed under a Creative Commons Attribution (CC-BY) 4.0 International Licence (https://www.hydrosheds.org)

ERA5-Land hourly data is publicly available in the Copernicus Climate Data Store (https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=overview)

The processing of HydroATLAS and ERA5 data was done using the Caravan GitHub repository (https://github.com/kratzert/Caravan.

### License

CC BY 4.0

### Additional context

The official network of gauging stations contains 1074 points. A selection has been made to remove stations with less than 8 years of data in the period 1991-2020, and those whose records show a clear alteration caused by the presence of reservoirs upstream. Unfortunately, after filtering, the distribution of catchments around the country is uneven, representing mostly the central and northern Spain. In the future I will explore the data sets from the water agencies, both to cover a larger part of the country and to explore if it would be possible to increase the temporal resolution of the time series.

![imagen](https://github.com/casadoj/CAMELS-ES_LSTM/blob/main/docs/fig1_seleccion_estaciones.jpg)
*Distribution of the selected and discarded gauging stations*

In addition to the usual attributes and time series that the Caravan notebooks generate, I have added new attributes and the simulated discharge from the recently released EFAS version 5 (European Flood Awareness System).

### Checklist

- [X] I have uploaded my dataset on Zenodo, where it is accessible under the DOI provided above.
- [X] I used a basin prefix that is not yet used by any other Caravan sub-dataset (you can check this via the [Data Contributions discussion thread](https://github.com/kratzert/Caravan/discussions/10), where all accepted Caravan contributions are listed).
- [X] Permissive License: My data is available under a license that is compatible with the Caravan CC-BY-4.0 license (the easiest way to be sure about this is if your data uses CC-BY-4.0, too).

**Comment by kratzert** [comment]
Hi Jesús,

thanks for contributing data to Caravan, much appreciated. I downloaded the data from Zenodo and had a quick look at it and here are a few things that I noticed.

- Naming of the extension: On Zenodo the dataset is named CAMELS-ES, but all extension folders are named `es` (rather than e.g. `camelses`. No problem from our side, just something I witnessed.
- No matter which extension name you pick, one thing that needs to be changed is that all gauge_ids in e.g. the attribute files and the shape files, but also the timeseries files, should always be `{extension_name}_{national_id}`. In your case, these are currently just what I assume is the national station id. This is important, because these national ids are not unique across the glob and otherwise it could happen that you have the same gauge_id for a gauge in Spain and e.g. Austria. So it would be great if you could rename the time series files and also make sure that all the gauge_ids in the attribute files and shape files are renamed. Depending on your choice in the previous point, this would e.g. be `es_1103.nc`, instead of `1103.nc` as of now.
- Regarding compatibility with the rest of Caravan, can you maybe remove all but the gauge_id field from the shape file? And strictly speaking, also the station shape file is not required, as this could be loaded from the `attributes_other_es.csv` file (which would also include the river name, country etc.
- The name of the basin shape file does not match the pattern we usually use in Caravan. Could you maybe rename the file to `{extension}_basin_shapes.shp` (`{extension}` depends on point 1).

Let me know what you think and/or once you updated the Zenodo repository.

**Comment by casadoj** [comment]
Hi Frederik,

I have created a version 1.0.1 with all the changes you suggested. I have chosen the extension `camelses`.

Let me know if I need to do any further change.

Regards.

**Comment by kratzert** [comment]
Hi,

checked the data again and all looks good. There is only one minor thing: The attribute files and the license file still end with `_es` instead of `_camelses`. We use to have the convention that we use the same short name of an extension everywhere (e.g. the gauge id has the same extension str added to the beginning as is used for folder names or in the attribute/license/shapefile file names.) 

So if you could rename those files that would be great. Everything else looks fine.

**Comment by casadoj** [comment]
Hi,

Sorry for the delay. The issue with the file names is fixed in the [version 1.0.2 of the Zenodo data set](https://zenodo.org/record/8428374).

Regards.

**Comment by casadoj** [comment]
Hi Frederik,

I've received your message about the new evapotranspiration time series and climate indices. I will work on it in the following days. I will also check if I can extend the time series; there are probably one or two years more of data available now.

**Comment by kratzert** [comment]
Amazing, thanks for the message.

**Comment by casadoj** [comment]
Hi Frederik,

Please find in this link a small update of the dataset (version 1.1.0) with the evapotranspiration change: https://zenodo.org/records/15040948

There's one more year of data available in the Ministry database, so I will create in the following weeks a newer version with this extra year. As I didn't want to delay more the ET fix, I submit now this new version.

Regards.

**Comment by kratzert** [comment]
Amazing, thanks for your effort. I already update the link in the Discussion post to point to the new version. Keep me update once you are able to add the additional streamflow data and many thanks in advance for your time spend on this.
